COMP: Fix missing header itkImageRegionConstIterator.h
BoneMorphometry/include/itkReplaceFeatureMapNanInfImageFilter.h:81:34:
error: no template named 'ImageRegionConstIterator' in namespace 'itk'